# Generated by Django 2.2.6 on 2022-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220413_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите новый текст', verbose_name='Текст'),
        ),
    ]
