# Generated by Django 2.2.16 on 2022-04-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220421_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите или отредактируйте текст', verbose_name='Текст'),
        ),
    ]
