# Generated by Django 2.2.16 on 2022-05-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20220517_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
