# Generated by Django 2.2.16 on 2022-05-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20220517_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
