# Generated by Django 2.2.16 on 2022-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20220527_1736'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupfollow',
            name='unique_follow',
        ),
        migrations.AddConstraint(
            model_name='groupfollow',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='group_unique_follow'),
        ),
    ]
