services:

  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - social_network_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env

  web:
    build: ../../yatube
    restart: always
    depends_on: 
      - db
    volumes:  
      - social_network_static_value:/app/static/      
      - social_network_media_value:/app/media/  
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345          
    env_file:
      - ../../.env     
  
  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web    
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - social_network_static_value:/var/html/static/
      - social_network_media_value:/var/html/media/      

volumes:
  social_network_postgres_data:   
  social_network_static_value: 
  social_network_media_value: 
