from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('authors/',
         views.authors,
         name='authors'),
    path('authors_follow/',
         views.authors_follow,
         name='authors_follow'),
    path('groups/',
         views.groups,
         name='groups'),
    path('groups_follow/',  # <str:username>/<int:flag>/',
         views.groups_follow,
         name='groups_follow'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('group/<slug:slug>/description',
         views.group_description,
         name='group_description'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('profile/<str:username>/following',
         views.profile_following,
         name='profile_following'),
    path('profile/<str:username>/follower',
         views.profile_follower,
         name='profile_follower'),
    path('profile/<str:username>/group_follower',
         views.profile_group_follower,
         name='profile_group_follower'),
    path('profile/<str:username>/comments',
         views.profile_comments,
         name='profile_comments'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/delete/',
         views.post_delete,
         name='post_delete'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('group/<slug:slug>/follow/',
         views.group_follow,
         name='group_follow'),
    path('group/<slug:slug>/unfollow/',
         views.group_unfollow,
         name='group_unfollow'),
]
